disabled_rules: # rule identifiers to exclude from running
  - variable_name
  - valid_docs
  - missing_docs
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
empty_count: severity: warning
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 130
# they can set both implicitly with an array
#type_body_length:
#  - 300 # warning
#  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
reporter: "csv" # reporter type (xcode, json, csv, checkstyle)
