disabled_rules: # rule identifiers to exclude from running
  - variable_name
  - valid_docs
  - missing_docs
opt_in_rules: # some rules are only opt-in
  - empty_count


# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
empty_count: severity: warning
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 130
file_length:
  warning: 500
#  error: 1200
reporter: "csv" # reporter type (xcode, json, csv, checkstyle)
